Repository svof/svof, pull requests merged in 2019-07, with the labels that each got.

#413 Fixes the ndb configs from not loading
  svo (install me in module manager).xml
  svo (namedb).xml
  svo (setup, misc, empty, funnies, dor).xml
Labels: in-client

#414 Offering update
  svo (offering).xml
Labels: in-client

#417 Blackout Fix
  svo (actions dictionary).xml
  svo (curing skeleton, controllers, action system).xml
Labels: in-client

#416 Added ndb.issoldier(name)
  doc/namedb.rst
  svo (namedb).xml
Labels: Documentation, enhancement

#422 Fixed some things listed under Issues
  svo (actions dictionary).xml
  svo (aliases, triggers).xml
  svo (install me in module manager).xml
  svo (setup, misc, empty, funnies, dor).xml
  svo (trigger functions).xml
Labels: in-client

#423 Deathsight Changes
  svo (actions dictionary).xml
Labels: in-client

#425 Sparks tracker removal
  svo (install me in module manager).xml
  svo (sparkstracker).xml
Labels: enhancement, in-client, low priority, simple difficulty

#432 Prompt cleanup
  svo (aliases, triggers).xml
  svo (namedb).xml
  svo (offering).xml
  svo (priestreport).xml
  svo (refiller).xml
  svo (stormhammertarget).xml
Labels: enhancement, in-client

#434 Harmony vibe added
  svo (aliases, triggers).xml
Labels: enhancement, in-client, medium priority, simple difficulty

#428 Serverside Deafaff and Blindaff fixes
  svo (actions dictionary).xml
  svo (curing skeleton, controllers, action system).xml
Labels: in-client

#435 Diagnose fix
  svo (alias and defence functions).xml
Labels: bug, high priority, in-client

#440 Pipe Changes
  svo (actions dictionary).xml
  svo (install, config, pipes, rift, parry, prios).xml
Labels: in-client

#437 Added Fire Lord, Water Lord, and Air Lord
  svo (actions dictionary).xml
  svo (alias and defence functions).xml
  svo (setup, misc, empty, funnies, dor).xml
Labels: in-client

#442 Transmute and Calcify Fixes
  svo (actions dictionary).xml
  svo (aliases, triggers).xml
  svo (trigger functions).xml
Labels: bug, high priority, in-client

#439 Shrugging enhancement
  svo (actions dictionary).xml
Labels: enhancement, in-client

#444 Prompt fix
  svo (limbcounter).xml
Labels: bug, enhancement, in-client, medium priority

#445 fix(harmonics-list): removed unnecessary white space from harmonics
  svo (aliases, triggers).xml
Labels: in-client

#443 Serverside sync error
  svo (custom prompt, serverside, peopletracker).xml
Labels: bug, in-client

#447 Alchemist tracking fix
  svo (aliases, triggers).xml
  svo (trigger functions).xml
Labels: in-client, medium priority

#450 CrushedThroatFix
  svo (trigger functions).xml
Labels: bug, in-client

#455 Blackout Fix
  svo (curing skeleton, controllers, action system).xml
Labels: bug, confirmed, high priority, in-client

#456 Limb counter changes
  svo (limbcounter).xml
Labels: enhancement, futher analysis needed, help wanted, in-client, medium difficulty, medium priority, up for grabs

#459 fix(dragonbreath-func): cleanup code for dragonbreath, use function from triggers
  svo (aliases, triggers).xml
  svo (install me in module manager).xml
  svo (trigger functions).xml
Labels: bug, in-client, medium priority

#463 quick stun fix
  svo (curing skeleton, controllers, action system).xml
Labels: bug, confirmed, in-client

#461 Added some defenses
  svo (alias and defence functions).xml
Labels: enhancement, in-client

#460 Dragonbreath tracking fix
  svo (actions dictionary).xml
Labels: bug, confirmed, high priority, in-client

#458 Unnameable logic
  svo (aliases, triggers).xml
  svo (install me in module manager).xml
Labels: enhancement, in-client

#462 Retain defs on classchange
  svo (install me in module manager).xml
Labels: bug, futher analysis needed, in-client, medium priority

#464 Fixes for Flail Staff
  svo (actions dictionary).xml
Labels: bug, confirmed, in-client

#465 Missed a comma
  svo (actions dictionary).xml
Labels: bug, confirmed, in-client

#466 Module Load Order
  svo (burncounter).xml
  svo (elistsorter).xml
  svo (enchanter).xml
  svo (fishdist).xml
  svo (inker).xml
  svo (limbcounter).xml
  svo (logger).xml
  svo (mindnet).xml
  svo (namedb).xml
  svo (offering).xml
  svo (peopletracker).xml
  svo (priestreport).xml
  svo (refiller).xml
Labels: enhancement, in-client

#469 Sentinel defence changes
  svo (actions dictionary).xml
  svo (alias and defence functions).xml
Labels: bug, confirmed, futher analysis needed

#472 Enchanter should properly load now
  svo (enchanter).xml
Labels: addons, enhancement

#476 Little fixes for the burn counter
  svo (burncounter).xml
Labels: addons, bug, in-client
