Repository svof/svof, pull requests merged in 2019-08, with the labels that each got.

#480 Added Pressure and Tension trigger functions
  svo (trigger functions).xml
Labels: in-client

#474 Temptrigger tables
  svo (alias and defence functions).xml
  svo (install me in module manager).xml
Labels: bug, in-client

#482 qwhom fix
  svo (peopletracker).xml
Labels: addons, bug, confirmed, in-client

#488 Limb Counter Update
  svo (limbcounter).xml
Labels: enhancement

#489 Small updates to Forestal and Monk
  svo (actions dictionary).xml
  svo (alias and defence functions).xml
Labels: bug, confirmed, high priority
