Repository svof/svof, pull requests merged in 2020-01, with the labels that each got.

#565 Update svo (namedb).xml
  svo (namedb).xml
Labels: in-client

#566 Fix for choleric humour stopping tree
  svo (aliases, triggers).xml
Labels: confirmed, medium priority

#573 Class Change Fixes
  svo (alias and defence functions).xml
  svo (install me in module manager).xml
Labels: bug, confirmed, high priority

#589 Update Limbcounter
  svo (limbcounter).xml
  svo (setup, misc, empty, funnies, dor).xml
Labels: confirmed, simple difficulty
